version: '3.9'

services:
  selenium-test:
    build:
      context: .
    ports:
      - "9100:8080"
    environment:
      - TEST_ENV=true
      - TARGET_URL=https://servicios.comedica.com.sv/ReportaCompraTC-war/